version: "3.9"
services:
  # api:
  #   build: .
  #   ports:
  #     - "${PORT}:${PORT}"
  db:
    image: postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres: